version: '2'
services:
  bundle:
    image: "lita-elasticsearch-indexer_server"
    volumes_from:
      - workdir
    entrypoint: ['bundle']
  rake:
    image: "lita-elasticsearch-indexer_server"
    volumes_from:
      - workdir
    entrypoint: ['rake']
  rspec:
    image: "lita-elasticsearch-indexer_server"
    environment:
      - LITA_REDIS_HOST=redis
      - LITA_ELASTICSEARCH_URL=elastic.local:9200
    volumes_from:
      - workdir
    links:
      - redis
      - elasticsearch:elastic.local
    entrypoint: ['rspec']
    command: spec
